### ISSUE TITLE
Recording doesn't restart when app gets killed

### ISSUE THREAD

**Issue by TurboLed** [HelgeApps/droid_dashcam_faq#13]
I have a Pixel 3 XL phone with only 4 GB RAM. Apps get killed constantly, including the Droid Dash Cam. Sometimes it restarts automatically, but recording doesn't restart. I'm looking for a solution for this.

**Comment by HelgeApps** [comment]
Please try to disable battery optimization for this app

**Comment by TurboLed** [comment]
Battery optimization would not solve it, because Android kills app to save memory regardless. But since then I changed my phone for a more recent one and now it works!
