### ISSUE TITLE
automatic video splitting during recording, without stopping recording

### ISSUE THREAD

**Issue by lpslp** [HelgeApps/droid_dashcam_faq#20]
hi
It **would be very nice** if "there" was such a feature as automatic video splitting into pieces (5 minutes 10 minutes 20 minutes - configurable) right during recording, without stopping recording. because writing 1 large long file is NOT safe + and if you have small files, "we" could automatically backup them.

**Comment by HelgeApps** [comment]
Hi. The app has video duration option at App/Settings/Other Settings

**Comment by lpslp** [comment]
this is exactly what I was looking for. 
Thank you.

**Comment by lpslp** [comment]
this is exactly what I was looking for. 
Thank you.
